package cloud

import (
	"context"
	"errors"
	"io"
	"time"
)

// ErrObjectNotFound is returned by StatObject/GetObject when the bucket holds
// no such key. It lets callers map a missing object to 404 without importing the
// storage SDK's own error types.
var ErrObjectNotFound = errors.New("object not found")

// ObjectInfo is the metadata of a stored object.
type ObjectInfo struct {
	Key         string
	Size        int64
	ContentType string
}

// Storage is the object-storage boundary of the upload pipeline. It is the
// valet-key model: the server never receives the bytes, it only hands the
// client a pre-signed URL, then inspects what landed.
type Storage interface {
	// PresignPut returns a pre-signed URL the browser can PUT the object to.
	// The signature covers the Host, so it must be generated by a client that
	// talks to the same endpoint the browser will.
	PresignPut(ctx context.Context, bucket, objectKey string, expiry time.Duration) (string, error)

	// StatObject returns metadata without downloading the body, or
	// ErrObjectNotFound.
	StatObject(ctx context.Context, bucket, objectKey string) (ObjectInfo, error)

	// GetObject streams the object. The caller closes it.
	GetObject(ctx context.Context, bucket, objectKey string) (io.ReadCloser, error)

	// Copy duplicates an object server-side, so the bytes never travel through
	// the app.
	Copy(ctx context.Context, srcBucket, srcObject, dstBucket, dstObject string) error

	// Remove deletes an object. Removing a missing object is not an error.
	Remove(ctx context.Context, bucket, objectKey string) error

	// PublicURL is the browser-facing URL of an object in a public-read bucket.
	// It performs no request and needs no credentials.
	PublicURL(bucket, objectKey string) string
}
